name: "Auto: Publisher"

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  check-tag:
    runs-on: ubuntu-latest
    # PRがマージされており、かつマージ元のブランチ名が一致する場合のみ実行
    if: (github.event.pull_request.merged == true && (startsWith(github.event.pull_request.head.ref, 'release/')))
    outputs:
      tag-name: ${{ steps.decide-tag-name.outputs.tag-name }}
    steps:
      - name: Decide tag name
        id: decide-tag-name
        env:
          # release/v1.0.0 のような文字列を取得
          RAW_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          # "release/" の部分を削除してタグ名（v1.0.0など）を抽出
          TAG_NAME=${RAW_BRANCH_NAME#release/}

          echo "Target tag name: $TAG_NAME"
          echo tag-name=$TAG_NAME >> "$GITHUB_OUTPUT"

  create-tag:
    needs: check-tag
    uses: ./.github/workflows/release-create-tag.yml
    with:
      version: ${{ needs.check-tag.outputs.tag-name }}
    secrets: inherit

  publish:
    needs: [check-tag, create-tag]
    uses: ./.github/workflows/release-publish.yml
    with:
      tag: ${{ needs.check-tag.outputs.tag-name }}
    secrets: inherit
