name: Release/Create Tag

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: "Tag Name"
        required: true
        type: string
      dry-run:
        required: false
        default: false
        type: boolean
        description: "Dry Run"
  workflow_call:
    inputs:
      tag-name:
        description: "Tag Name"
        required: false
        type: string

jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: inputs.tag-name != ''
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #6.0.1

      - name: Check existing tags
        run: |
          git fetch --prune --unshallow --tags
          count=$(git tag -l "${{ inputs.tag-name }}" | wc -l)
          echo $count
          if [ $count -gt 0 ]; then
            echo "Tag ${{ inputs.tag-name }} already exists"
            exit 1
          fi

      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # タグの作成
          git tag ${{ inputs.tag-name }}

          if [ "${{ inputs.dry-run }}" != "true" ]; then
            git push origin ${{ inputs.tag-name }}
          else
            echo "Dry run enabled: Skipping tag push"
          fi
