name: Run Unit Test Manually

on:
  workflow_dispatch:
    inputs:
      coverage:
        description: "カバレッジ集計を行ってテストするか"
        required: false
        default: false
        type: boolean

jobs:
  Test:
    uses: ./.github/workflows/jest-runner.yml
    with:
      collect-coverage: inputs.coverage
    secrets: inherit
