name: Run Unit Test Manually

on:
  workflow_call:
    inputs:
      coverage:
        required: false
        default: false
        type: boolean

jobs:
  Test:
    uses: ./.github/workflows/jest-runner.yml
    if: |
      github.event.pull_request.draft == false
      && !startsWith(github.head_ref, 'release')
    with:
      collect-coverage: inputs.coverage
    secrets: inherit
